ALTER TABLE veiculo ADD COLUMN cidade VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE veiculo ADD COLUMN estado VARCHAR(2) NOT NULL DEFAULT '';
ALTER TABLE veiculo ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE veiculo ADD COLUMN longitude DOUBLE PRECISION;